#!/bin/sh
set -eu
if test "${1:-}" = --owntransit-development-test; then
  exit 0
fi
if test "$*" = 'show owntransit-connector-pair.service --property=DropInPaths --value'; then exit 0; fi
if test "$*" = 'disable --now owntransit-connector-pair.service'; then exit 0; fi
test "$#" -eq 1 && test "$1" = daemon-reload || exit 90
printf '%s\n' daemon-reload >> /tmp/owntransit-development-systemctl.calls
